### ISSUE TITLE
Pop-up really slow to load the data.

### ISSUE THREAD

**Issue by mikhoul** [davidnguyen179/spotify-extension#107]
I really like this extension but the loading time of the data is really long, could it be improved by having an option to preload the data it in the background when the spotify player is loaded on a tab instead of loading the data only on the mouse click ?

Look here: http://screencast-o-matic.com/watch/creTYOVVtvD

Regards :octocat:

**Comment by davidnguyen179** [comment]
Thank you very much @mikhoul, I really appreciate it. I am finding the way to improve it, but it could take me sometime to optimize the whole plugin. So far, I've made some improvements like reduce API calls. Here is the result I measured before & after improve

```bash
before

render time: 372.52197265625 ms
render time: 369.032958984375 ms
after

render time: 165.0390625 ms
render time: 163.19580078125 ms
```
