### ISSUE TITLE
Add the option to open the popup in a new windows.

### ISSUE THREAD

**Issue by mikhoul** [davidnguyen179/spotify-extension#127]
@davidnguyen179 

**Is your feature request related to a problem? Please describe.**
Sometime I like to see the art album, title name of the song when the music play just by looking at the GUI without the need to do any action

**Describe the solution you'd like**
Adding a button in the popup to allow to open it inside it's ow window like this extension in the screenshot:

![image](https://user-images.githubusercontent.com/5678673/115161727-50a80480-a06d-11eb-806c-9c29bf6799a8.png)

**The popup inside his own window:** 

![image](https://user-images.githubusercontent.com/5678673/115161785-9664cd00-a06d-11eb-8a7b-cb11b0a32378.png)

Best Regards  :octocat:

**Comment by davidnguyen179** [comment]
actually you can click on the song name, it'll open web player in another tab

**Comment by mikhoul** [comment]
I know but the goal here is to be able to see the song/artist/etc without the need to click on anything or open something.

This way my workflow is not interrupted, I could look quickly at the small window to see the information without stopping my task.  :smile:
