### ISSUE TITLE
Add pre-commit & pre-push in git hook 

### ISSUE THREAD

**Issue by davidnguyen179** [davidnguyen179/spotify-extension#46]
**pre-commit**

- run prettier

**pre-push**

- run unit test with coverage
```bash
npm test -- --coverage
```

use this package
https://www.npmjs.com/package/git-hooks-plus

**Comment by davidnguyen179** [comment]
https://www.npmjs.com/package/git-hooks-plus

**Comment by immint023** [comment]
i take this one

**Comment by davidnguyen179** [comment]
If you do the `prettier` for git book. Please refer this link https://prettier.io/docs/en/precommit.html#option-5-shell-script

@immint023
