### ISSUE TITLE
[Bug] UI doesn't update when autoplay to next song

### ISSUE THREAD

**Issue by haoict** [davidnguyen179/spotify-extension#5]
![image](https://user-images.githubusercontent.com/7247750/83607928-ffa73300-a5b6-11ea-9e80-ab942dd5c46b.png)

Above screenshot:
- Tab: South of the Border (current playing song)
- Popup view of extension: No Sleep (last song)

Suggest solution:
- I think it's hard to create action listener when next song is automatically triggered, instead you can `setInterval` to check currently playing song, or get song's duration then `setTimeout` by that time to update playing song

**Comment by davidnguyen179** [comment]
This issue has been fixed by this PR https://github.com/davidnguyen179/spotify-extension/pull/10
