### ISSUE TITLE
Add volume control UI

### ISSUE THREAD

**Issue by davidnguyen179** [davidnguyen179/spotify-extension#58]

**Comment by mikhoul** [comment]
Hi,

I was looking for an extension with a  "mini player" for Spotify with a volume so as soon you implement it I will use it.

A suggestion for the volume control:  I would really like to be able  to control the volume with the mouse scroll wheel:   When the cursor would be inside the mini-player and we scroll mouse button up the volume raise and vice-versa for lower the volume.

No need to click and move a slider to adjust the volume, and it's more precise too.


Regards :octocat:

**Comment by davidnguyen179** [comment]
Well I guess you can use it now. The v1.17 is out and it contains the volume control
