### ISSUE TITLE
Controlling iPhone Spotify through chrome(web.spotify.com)?

### ISSUE THREAD

**Issue by ctklainow** [davidnguyen179/spotify-extension#71]
Is it possible to use this chrome extension to control Spotify while it's playing on your iPhone?

Thanks david!

**Comment by davidnguyen179** [comment]
Hi, thanks for using this extension. It's possible to control music from ur devices via this extension. However, the purpose of this extension is only for browser to improve stability.

**Comment by ctklainow** [comment]
Ah ok, thanks!
